//! Git stash operations via git2 (CHI-326).

use crate::AppError;
use std::path::Path;

/// A single stash entry.
#[derive(Debug, Clone, serde::Serialize)]
pub struct StashEntry {
    /// 0-based index into the stash list (stash@{0} = 0, stash@{1} = 1, ...).
    pub index: usize,
    /// Stash message (may include autogenerated text from git2).
    pub message: String,
    /// Full 40-char OID of the stash commit.
    pub oid: String,
}

/// List all stash entries, ordered from most recent (index 0) to oldest.
pub fn list_stashes(repo_root: &Path) -> Result<Vec<StashEntry>, AppError> {
    let mut repo = git2::Repository::open(repo_root).map_err(|e| AppError::Git(e.to_string()))?;

    let mut entries = Vec::new();
    repo.stash_foreach(|index, message, oid| {
        entries.push(StashEntry {
            index,
            message: message.to_string(),
            oid: oid.to_string(),
        });
        true
    })
    .map_err(|e| AppError::Git(e.to_string()))?;

    Ok(entries)
}

/// Push a new stash. Uses git default signature from repo config.
/// `include_untracked` controls whether untracked files are included.
/// Returns the OID of the new stash commit.
pub fn push_stash(
    repo_root: &Path,
    message: &str,
    include_untracked: bool,
) -> Result<String, AppError> {
    let mut repo = git2::Repository::open(repo_root).map_err(|e| AppError::Git(e.to_string()))?;

    let sig = repo.signature().map_err(|e| AppError::Git(e.to_string()))?;
    let flags = if include_untracked {
        git2::StashFlags::INCLUDE_UNTRACKED
    } else {
        git2::StashFlags::DEFAULT
    };

    let oid = repo
        .stash_save(&sig, message, Some(flags))
        .map_err(|e| AppError::Git(format!("Stash save failed: {}", e)))?;

    Ok(oid.to_string())
}

/// Apply a stash by index (does NOT drop it from the stash list).
pub fn apply_stash(repo_root: &Path, index: usize) -> Result<(), AppError> {
    let mut repo = git2::Repository::open(repo_root).map_err(|e| AppError::Git(e.to_string()))?;

    let mut opts = git2::StashApplyOptions::new();
    repo.stash_apply(index, Some(&mut opts))
        .map_err(|e| AppError::Git(format!("Stash apply failed: {}", e)))
}

/// Pop a stash by index (apply + drop atomically).
pub fn pop_stash(repo_root: &Path, index: usize) -> Result<(), AppError> {
    let mut repo = git2::Repository::open(repo_root).map_err(|e| AppError::Git(e.to_string()))?;

    let mut opts = git2::StashApplyOptions::new();
    repo.stash_pop(index, Some(&mut opts))
        .map_err(|e| AppError::Git(format!("Stash pop failed: {}", e)))
}

/// Drop a stash entry by index (discards it permanently).
pub fn drop_stash(repo_root: &Path, index: usize) -> Result<(), AppError> {
    let mut repo = git2::Repository::open(repo_root).map_err(|e| AppError::Git(e.to_string()))?;

    repo.stash_drop(index)
        .map_err(|e| AppError::Git(format!("Stash drop failed: {}", e)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;
    use tempfile::TempDir;

    fn init_repo_with_file() -> TempDir {
        let dir = TempDir::new().unwrap();
        Command::new("git")
            .args(["init", "-b", "main"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.email", "t@t.com"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.name", "T"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        std::fs::write(dir.path().join("file.txt"), "original\n").unwrap();
        Command::new("git")
            .args(["add", "."])
            .current_dir(dir.path())
            .output()
            .unwrap();
        Command::new("git")
            .args(["commit", "-m", "init"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        dir
    }

    #[test]
    fn test_list_stashes_empty() {
        let dir = init_repo_with_file();
        let stashes = list_stashes(dir.path()).unwrap();
        assert!(stashes.is_empty());
    }

    #[test]
    fn test_push_stash_creates_entry() {
        let dir = init_repo_with_file();
        std::fs::write(dir.path().join("file.txt"), "modified\n").unwrap();

        push_stash(dir.path(), "test stash", false).unwrap();

        let stashes = list_stashes(dir.path()).unwrap();
        assert_eq!(stashes.len(), 1);
        assert!(stashes[0].message.contains("test stash"));
        assert_eq!(stashes[0].index, 0);
    }

    #[test]
    fn test_push_stash_cleans_working_tree() {
        let dir = init_repo_with_file();
        std::fs::write(dir.path().join("file.txt"), "modified\n").unwrap();

        push_stash(dir.path(), "save", false).unwrap();

        let content = std::fs::read_to_string(dir.path().join("file.txt")).unwrap();
        assert_eq!(content, "original\n");
    }

    #[test]
    fn test_pop_stash_restores_changes() {
        let dir = init_repo_with_file();
        std::fs::write(dir.path().join("file.txt"), "stashed\n").unwrap();
        push_stash(dir.path(), "save", false).unwrap();

        pop_stash(dir.path(), 0).unwrap();

        let content = std::fs::read_to_string(dir.path().join("file.txt")).unwrap();
        assert_eq!(content, "stashed\n");
        assert!(list_stashes(dir.path()).unwrap().is_empty());
    }

    #[test]
    fn test_drop_stash_removes_entry() {
        let dir = init_repo_with_file();
        std::fs::write(dir.path().join("file.txt"), "changed\n").unwrap();
        push_stash(dir.path(), "save", false).unwrap();
        assert_eq!(list_stashes(dir.path()).unwrap().len(), 1);

        drop_stash(dir.path(), 0).unwrap();

        assert!(list_stashes(dir.path()).unwrap().is_empty());
    }

    #[test]
    fn test_apply_stash_does_not_drop() {
        let dir = init_repo_with_file();
        std::fs::write(dir.path().join("file.txt"), "stashed\n").unwrap();
        push_stash(dir.path(), "save", false).unwrap();

        apply_stash(dir.path(), 0).unwrap();

        let stashes = list_stashes(dir.path()).unwrap();
        assert_eq!(stashes.len(), 1);
        let content = std::fs::read_to_string(dir.path().join("file.txt")).unwrap();
        assert_eq!(content, "stashed\n");
    }
}
