//! Diagnostic bundle export (CHI-96).
//!
//! Collects redacted ring-buffer logs and system metadata into a ZIP archive for
//! bug reports and support workflows.

use std::io::Write;
use std::path::PathBuf;

use serde::Serialize;
use zip::write::SimpleFileOptions;
use zip::ZipWriter;

use super::init::get_ring_buffer;
use super::redactor::{LogRedactor, RedactionSummary};
use super::ring_buffer::LogEntry;

/// System information snapshot included in the diagnostic bundle.
#[derive(Debug, Clone, Serialize)]
pub struct SystemInfo {
    pub app_version: String,
    pub os: String,
    pub arch: String,
    pub timestamp: String,
}

impl SystemInfo {
    pub fn collect() -> Self {
        Self {
            app_version: env!("CARGO_PKG_VERSION").to_string(),
            os: std::env::consts::OS.to_string(),
            arch: std::env::consts::ARCH.to_string(),
            timestamp: chrono::Utc::now().to_rfc3339(),
        }
    }
}

/// Result returned to the frontend after exporting a diagnostic bundle.
#[derive(Debug, Clone, Serialize)]
pub struct BundleExportResult {
    pub path: String,
    pub size_bytes: u64,
    pub log_entry_count: usize,
    pub redaction: RedactionSummary,
}

fn zip_error(err: zip::result::ZipError) -> crate::AppError {
    crate::AppError::Other(format!("ZIP export error: {}", err))
}

/// Export a redacted diagnostic bundle ZIP to the log directory `exports/` folder.
pub fn export_bundle() -> Result<BundleExportResult, crate::AppError> {
    let ring_buffer = get_ring_buffer().ok_or_else(|| {
        crate::AppError::Other("Logging not initialized — cannot export bundle".to_string())
    })?;

    let entries: Vec<LogEntry> = {
        let buf = ring_buffer.lock();
        buf.iter().cloned().collect()
    };

    let redactor = LogRedactor::new();
    let (redacted_entries, redaction_summary) = redactor.redact_entries(&entries);
    let system_info = SystemInfo::collect();

    let export_dir = export_directory();
    std::fs::create_dir_all(&export_dir).map_err(|e| {
        crate::AppError::Io(std::io::Error::new(
            e.kind(),
            format!("Failed to create export directory {:?}: {}", export_dir, e),
        ))
    })?;

    let timestamp = chrono::Utc::now().format("%Y%m%d-%H%M%S");
    let zip_filename = format!("chiefwiggum-diagnostic-{}.zip", timestamp);
    let zip_path = export_dir.join(zip_filename);

    let file = std::fs::File::create(&zip_path)?;
    let mut zip = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    zip.start_file("logs.jsonl", options).map_err(zip_error)?;
    for entry in &redacted_entries {
        let line = serde_json::to_string(entry)?;
        zip.write_all(line.as_bytes())?;
        zip.write_all(b"\n")?;
    }

    zip.start_file("system_info.json", options)
        .map_err(zip_error)?;
    let system_json = serde_json::to_string_pretty(&system_info)?;
    zip.write_all(system_json.as_bytes())?;

    zip.start_file("redaction_summary.json", options)
        .map_err(zip_error)?;
    let redaction_json = serde_json::to_string_pretty(&redaction_summary)?;
    zip.write_all(redaction_json.as_bytes())?;

    zip.start_file("README.txt", options).map_err(zip_error)?;
    let readme = format!(
        "Chief Wiggum Diagnostic Bundle\n\
         ==============================\n\n\
         This archive contains diagnostic information for bug reports.\n\
         Sensitive values in logs (API keys, emails, local paths) are redacted.\n\n\
         Contents:\n\
         - logs.jsonl              Redacted application logs (JSON Lines)\n\
         - system_info.json        OS and application version metadata\n\
         - redaction_summary.json  Summary of redaction rules applied\n\
         - README.txt              This file\n\n\
         Generated by Chief Wiggum v{}\n",
        env!("CARGO_PKG_VERSION")
    );
    zip.write_all(readme.as_bytes())?;

    zip.finish().map_err(zip_error)?;

    let metadata = std::fs::metadata(&zip_path)?;

    Ok(BundleExportResult {
        path: zip_path.to_string_lossy().to_string(),
        size_bytes: metadata.len(),
        log_entry_count: redacted_entries.len(),
        redaction: redaction_summary,
    })
}

/// Platform-aware export directory (subfolder of the app log directory).
fn export_directory() -> PathBuf {
    super::init::log_directory_path().join("exports")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn system_info_collects_valid_data() {
        let info = SystemInfo::collect();
        assert!(!info.app_version.is_empty());
        assert!(!info.os.is_empty());
        assert!(!info.arch.is_empty());
        assert!(!info.timestamp.is_empty());
    }

    #[test]
    fn export_directory_is_inside_log_directory() {
        let export = export_directory();
        let log = super::super::init::log_directory_path();
        assert!(export.starts_with(&log));
    }

    #[test]
    fn export_directory_ends_with_exports() {
        let dir = export_directory();
        assert!(dir.ends_with("exports"));
    }
}
